### ISSUE TITLE
command 'hide-files.show' not found

### ISSUE THREAD

**Issue by Martinspire** [JeremyFunk/hidefiles#15]
I have the extension installed and use a global setup to not override the repository settings and have more control over what I hide vs what my teammates want to see, but it seems to bug out when I want to show all files or toggle a different profile.

I get an error notification (bottom right corner) with the text:
`command 'hide-files.show' not found`

I can however toggle files inside my default (active) configuration and I do see files being hidden from that configuration. I just can't toggle all or switch to a different profile.

My config right now:

```

  "hidefiles.globalConfig": {
    "profiles": [
      {
        "name": "Default",
        "detail": "",
        "description": "Test",
        "hidden": [
          ".vscode/",
          "node_modules/",
			...
        ],
        "peek": [
          ...
        ]
      },
      {
        "hidden": [],
        "name": "All",
        "description": "",
        "detail": "",
        "peek": []
      }
    ]
  },
  "hidefiles.version": "2.0.0",
```

I also have this exclusion list:

```
  "files.exclude": {
    "**/.vscode": false,
    "node_modules": false
	...
  },
```

I'm not sharing the entire list as I don't think it makes a difference. I don't see any other error messages other than in the Extension Host:

`2024-06-11 12:46:26.076 [error] Error: command 'hide-files.show' not found
    at v.n (vscode-file://vscode-app/<path>/resources/app/out/vs/workbench/workbench.desktop.main.js:1637:23867)
    at v.executeCommand (vscode-file://vscode-app/<path>/resources/app/out/vs/workbench/workbench.desktop.main.js:1637:23796) hide-files.show undefined`
<path>  is my windows installation folder

According to a github issue on VSCode, it might have to do with the registration of the command: https://stackoverflow.com/questions/49534068/command-not-found-in-vscode-extension

And indeed, I don't see it mentioned here:
https://github.com/JeremyFunk/hidefiles/blob/master/package.json#L14

**Comment by ThaDaVos** [comment]
Having same error - and seeing as there's no response from the author a year later, I guess it's no longer maintained...

**Comment by Martinspire** [comment]
> Having same error - and seeing as there's no response from the author a year later, I guess it's no longer maintained...

Yeah I also uninstalled it, unfortunately. It looked like a neat solution but got broken rather quickly.

**Comment by Martinspire** [comment]
Doubt this will get fixed...
